
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jan 22 15:57:39 BRST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int EQ = 6;
  public static final int RPAREN = 5;
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int NUMBER = 7;
  public static final int LPAREN = 4;
  public static final int TIMES = 3;
  public static final int EOF = 0;
}

