
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 19 10:01:47 BRST 2016
//----------------------------------------------------

package br.com.johnidouglas;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int FECHA_PARENTESES = 17;
  public static final int PONTO_E_VIRGULA = 12;
  public static final int ATE = 5;
  public static final int MULTIPLICACAO = 9;
  public static final int DOIS_PONTOS = 13;
  public static final int PARA = 4;
  public static final int ID = 8;
  public static final int VIRGULA = 18;
  public static final int ATRIBUICAO = 10;
  public static final int FUNCAO = 15;
  public static final int ABRE_PARENTESES = 16;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NUMERO = 7;
  public static final int FACA = 6;
  public static final int VARIAVEL = 11;
  public static final int FIM = 3;
  public static final int TIPO_INTEIRO = 14;
  public static final int INICIO = 2;
}

